[[plugins]]
package = "netlify-plugin-to-all-events"
  [plugins.inputs]
  triggerAll = true
  keyword = "toshi"
  databaseUrl = "https://database.com/v1/projects/1234/db/thingy"

[[plugins]]
package = "./plugins/netlify-test-plugin"

[context.deploy-preview.environment]
    VARIABLE = "hello"
    environment = { IS_DEPLOY_PREVIEW = "true"}